name: Build Windows EXE with PyInstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --add-data "index.html:." main.py --name operafor
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: operafor-exe
          path: dist/operafor.exe
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            Téléchargez l'exécutable ici :
            [operafor.exe](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
